travis:
  secure:
    BINSTAR_TOKEN: i1rbROIQzWq2dKJXjjdF3gPIBRcx8LWaHehDFP1kUKWP69Ew+djy8rWaTkf3Xc/xoRisyoG6C+kMiGvSXetl2AO3iUKgEtaX/G2z3lvcvoNmgd9FYFh7q0sKrDGnErx/RHKt9yeVUw/ZCmyianelbO2TaSPFDWhVYD4j7kgADO6FJyZKYu9jLKwZKnXgtAvm0wHgzugC+3SkPvFe8YnWfUElkEjXPUMccT7xm7OTWdxasEiu+ky1H6+2hTXpa2V/i+WaDJrzhMh14/cFdMbeca0pEh9Kx5NL2Rc77pPzQMHg4tmp6iiurffM74YVlBdZXqzsHDIOAkOHCtAaXFUhitH/1fyjGB9b3h+9AMPiUyd9sZGGZEaEDL14pnLHpr6zLenSI5RaAJDbT7CS677xxP5ZNV5rwvFm4wcwzw9ObrDDvUx914c9SJxbqcpKAIKmezq3Z2tGuo0M7ghYnT4urXZ8X/T+ctAEtF3Ha6Fmx/csW3yHTgmnK4ZHfl1D6s7SlFcmAYpjKHYTV05KTaa8lGfDb9iLlOa1hC48B3t6WDX1Z23en2sKkgZR+cOCGh/htDKNIqyyQZYyJU/iz3wGCmAyow36BRlw431R6PH7SJCa/4C2hnsH/OVN0Nt8BTJBzaG9G81divaMCzo+MNoSGmDB9jVUXsyO40Czj/nycEs=
appveyor:
  secure:
    BINSTAR_TOKEN: MP4hZYylDyUWEsrt3u3cod2sbFeRwUziH02mvQOdbjsTO/l1yIxDkP/76rSIjcGC
